version: '3.8'

services:
  swiftbot:
    image: swiftbot:latest
    build: .
    networks:
      - swiftbot_rede
    environment:
      - NODE_ENV=production
      - PORT=3000
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.swiftbot-secure.rule=Host(`swiftbot.com.br`) || Host(`www.swiftbot.com.br`)"
        - "traefik.http.routers.swiftbot-secure.entrypoints=websecure"
        - "traefik.http.routers.swiftbot-secure.tls=true"
        - "traefik.http.routers.swiftbot-secure.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.swiftbot.loadbalancer.server.port=3000"

networks:
  swiftbot_rede:
    external: true
